generator:
  class: sfPropelGenerator
  param:
    model_class:           PxeFile
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              PxeFile
    plural:                PxeFiles
    route_prefix:          pxe_file
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Gestion des fichiers PXE
        display: [=filename, description]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
