all:
  cas_server:
    host: cas.univ-avignon.fr
    port: 443
    path:
   
  ldap_server:
    host: ldap.univ-avignon.fr
    port: 389
    basedn: dc=univ-avignon,dc=fr
    options: {<?php echo LDAP_OPT_PROTOCOL_VERSION ?>: 3}
  
  profile:
    var_translation:
      fullname: displayname

  const:
    max_per_page: [ 50, 100, All ]

dev:
  security:
    gods: [marcelf]
