image:
  class: sfPropel15RouteCollection
  options:
    model:                Image
    module:               image
    prefix_path:          /image
    column:               id
    with_wildcard_routes: true

image_restore:
  url:   /restore
  param: { module: image, action: restore }

add_pxe:
  url:    /addPxe
  param:  { module: pxe_file, action: add }

csv_export:
  url:    /csvExport
  param:  { module: host, action: export }

csv_import:
  url:    /csvImport
  param:  { module: host, action: import }

image_server:
  class: sfPropel15RouteCollection
  options:
    model:                ImageServer
    module:               image_server
    prefix_path:          /image_server
    column:               id
    with_wildcard_routes: true

subnet:
  class: sfPropel15RouteCollection
  options:
    model:                Subnet
    module:               subnet
    prefix_path:          /subnet
    column:               id
    with_wildcard_routes: true

pxe_file:
  class: sfPropel15RouteCollection
  options:
    model:                PxeFile
    module:               pxe_file
    prefix_path:          /pxe_file
    column:               id
    with_wildcard_routes: true

profile:
  class: sfPropel15RouteCollection
  options:
    model:                Profile
    module:               profile
    prefix_path:          /profile
    column:               id
    with_wildcard_routes: true

host:
  class: sfPropel15RouteCollection
  options:
    model:                Host
    module:               host
    prefix_path:          /host
    column:               id
    with_wildcard_routes: true

room:
  class: sfPropel15RouteCollection
  options:
    model:                Room
    module:               room
    prefix_path:          /room
    column:               id
    with_wildcard_routes: true

command_list:
  url:   /command
  param: { module: command, action: index }

command_svn_status:
  url:   /commande/status
  param: { module: command, action: svnStatus }

command_show:
  url:     /command/:id
  class:   sfPropel15Route
  options: { model: Command, type: object }
  param:   { module: command, action: show }
  requirements:
    id: \d+
    sf_method: [get]

command_stop:
  url:     /command/:id/stop
  class:   sfPropel15Route
  options: { model: Command, type: object }
  param:   { module: command, action: stop }
  requirements:
    id: \d+
    sf_method: [get]

dns_show:
  url:   /dns/:filename
  param: { module: dns, action: show }
  requirements:
    filename: db.*

image_server_stop:
  url:   /image_server/:id/stop
  class:   sfPropel15Route
  options: { model: ImageServer, type: object }
  param: { module: dns, action: show }

image_server_status:
  url:   /image_server/:id/status
  class:   sfPropel15Route
  options: { model: ImageServer, type: object }
  param: { module: dns, action: status }

inDnsCheck:
  url:    /host/inDns
  param:  { module: host, action: inDns }

inDnsHostname:
  url:    /host/inDnsHostname
  param:  { module: host, action: inDnsHostname }

commentProfil:
  url:    /host/commentProfil
  param:  { module: host, action: commentProfil }

# default rules
homepage:
  url:   /
  param: { module: command, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
