image_server:
  class: sfPropel15RouteCollection
  options:
    model:                ImageServer
    module:               image_server
    prefix_path:          /image_server
    column:               id
    with_wildcard_routes: true

subnet:
  class: sfPropel15RouteCollection
  options:
    model:                Subnet
    module:               subnet
    prefix_path:          /subnet
    column:               id
    with_wildcard_routes: true

pxe_file:
  class: sfPropel15RouteCollection
  options:
    model:                PxeFile
    module:               pxe_file
    prefix_path:          /pxe_file
    column:               id
    with_wildcard_routes: true

profile:
  class: sfPropel15RouteCollection
  options:
    model:                Profile
    module:               profile
    prefix_path:          /profile
    column:               id
    with_wildcard_routes: true

host:
  class: sfPropel15RouteCollection
  options:
    model:                Host
    module:               host
    prefix_path:          /host
    column:               id
    with_wildcard_routes: true

room:
  class: sfPropel15RouteCollection
  options:
    model:                Room
    module:               room
    prefix_path:          /room
    column:               id
    with_wildcard_routes: true

command_start:
  url:     /command/:id
  class:   sfPropel15Route
  options: { model: Command, type: object }
  param:   { module: command, action: start }
  requirements:
    id: \d+
    sf_method: [get]

command_stop:
  url:     /command/:id
  class:   sfPropel15Route
  options: { model: Command, type: object }
  param:   { module: command, action: stop }
  requirements:
    id: \d+
    sf_method: [get]

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
