generator:
  class: sfPropelGenerator
  param:
    model_class:           Subnet
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              Subnet
    plural:                Subnets
    route_prefix:          subnet
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        range_begin:    { label: Dynamic range begin }
        range_end:      { label: Dynamic range end }
      list:
        title: Gestion des subnets
        display: [=name, ip_address, netmask, domain_name, dns_server, image_server, pxe_file]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
