generator:
  class: sfPropelGenerator
  param:
    model_class:           Host
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              Host
    plural:                Hosts
    route_prefix:          host
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        hostname:     { label: Nom }
        ip_address:   { label: Adresse Ip }
        mac_address:  { label: Adresse Mac }
        subnet:       { label: Subnet }
        pxe:          { label: Fichier Pxe }
      list:
        title: Gestion des machines
        display: [=hostname, ip_address, mac_address, subnet, pxe]
        max_per_page: 50
        batch_actions:
          _delete:    ~
          restore:    { label: Restaurer une image }
          addPxe:     { label: Modifier la conf PXE }
          ping:       { label: Tester le DNS et l\'état des machines }
        object_actions:
          createImage:     { label: Créer une image }
          _edit:      ~
          _delete:    ~
      filter:
        display: [profile_id, room_id, subnet_id, ip_address, mac_address, pxe_file_id]
      form:    ~
      edit:    ~
      new:     ~
