<?php



/**
 * Skeleton subclass for representing a row from the 'command' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.1-dev on:
 *
 * Wed May 25 23:31:12 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Command extends BaseCommand {

  /**
   * Exécute la commande en créant un fork et en redirigeant la sortie standart et d'errreur vers
   * des fichiers temporaires.
   *
   * Enregistre la commande en base également
   *
   * @return void
   */
  public function exec ()
  {
    $this->setStdErrFile (tempnam ('/tmp','manitou_cmd_'));
    $this->setStdOutFile (tempnam ('/tmp','manitou_cmd_'));
    $this->save();

    $command = $this->getCommand()
      .' 2> '.$this->getStdErrFile()
      .'  > '.$this->getStdOutFile();

    exec($command, $result, $returnVal);

    $this->setStdErr (file_get_contents ($this->getStdErrFile()));
    $this->setStdOut (file_get_contents ($this->getStdOutFile()));
    $this->setReturnCode ($returnVal);
    $this->save();

    unlink($this->getStdErrFile());
    unlink($this->getStdOutFile());
  }

  public function isRunning ()
  {
    return ($this->getReturnCode() === null);
  }

} // Command
