<?php



/**
 * Skeleton subclass for performing query and update operations on the 'host' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.1-dev on:
 *
 * Mon May 23 21:11:36 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class HostQuery extends BaseHostQuery {

  /**
   * @param $hostname     example "etd-2w18-121"
   * @return Host
   */
  public function findByHostname ($hostname)
  {
    list ($profile, $room, $number) = explode ('-', $hostname);
    return $this->filterByNumber($number)
                ->useProfileQuery()
                  ->filterByName($profile)
                ->endUse()
                ->useRoomQuery()
                  ->filterByName($room)
                ->endUse()
                ->findOne();
  }

  public function filterByContain ($query)
  {
      return $this->joinProfile()
                    ->joinRoom()
                    ->where("CONCAT(profile.name,'-',room.name,'-',host.number) REGEXP '".$query."' OR host.id REGEXP '".$query."' OR host.ip_address REGEXP '".$query."' OR host.mac_address REGEXP '".$query."' OR host.number REGEXP '".$query."' OR host.comment REGEXP '".$query."' ")
                    ->find();
  }

} // HostQuery
