<?php



/**
 * Skeleton subclass for representing a row from the 'host' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.1-dev on:
 *
 * Mon May 23 21:11:36 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Host extends BaseHost {

  public function __toString () {
    return $this->getHostname ();
  }

  public function getHostname () {
    return $this->getProfile().'-'.$this->getRoom ().'-'.$this->getNumber ();
  }

	/**
	 * Code to be run before persisting the object
   *
   * On exécute alors la commande ns-update
   *
	 * @param PropelPDO $con
	 */
	public function preSave(PropelPDO $con = null)
  {
    // TODO récupérer les anciennes valeurs et ne déclancher la commande
    // que si l'hostname a changé

    return parent::preSave($con);
  }

	/**
	 * Code to be run after persisting the object
   *
   * On exécute alors la commande de mise à jour du DHCP
   *
	 * @param PropelPDO $con
	 */
	public function postSave(PropelPDO $con = null)
  {
    CommandPeer::runDhcpdUpdate();
    return parent::postSave($con);
  }

} // Host
