<?php



/**
 * Skeleton subclass for representing a row from the 'image' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.1-dev on:
 *
 * Wed May 25 00:43:58 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Image extends BaseImage {

  public function create ()
  {
    $script = sfConfig::get('sf_manitou_create_image_command');
    $script = str_replace(
      array('%filename%', '%ip%', '%mac%', '%restart%'),
      array($this->getFilename(), $this->getHost()->getIpAddress(), $this->getHost()->getMacAddress(), $this->getRestart()),
      $script
    );

    $command = new Command();
    $command->setCommand($script);
    $command->setUserId ('foobar'); // TODO
    $command->save();
    $command->backgroundExec ();
  }

} //ge
