<?php



/**
 * Skeleton subclass for representing a row from the 'image_server' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.1-dev on:
 *
 * Wed May 25 22:30:45 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ImageServer extends BaseImageServer {

  public function __toString () {
    return $this->getName ();
  }

} // ImageServer
