<?php



/**
 * Skeleton subclass for representing a row from the 'pxe_file' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.1-dev on:
 *
 * Mon May 23 21:11:36 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class PxeFile extends BasePxeFile {

  public function __toString () {
    return $this->getName ();
  }

} // PxeFile
