propel:

  subnet:
    id: ~
    name:             { type: varchar, size: 30 }
    ip_address:       { type: varchar, size: 15, required: true }
    netmask:          { type: varchar, size: 15, required: true }
    server_interface: { type: varchar, size: 5,  required: true }
    custom_conf:      { type: longvarchar }
    image_server_id:  ~
    pxe_file_id:      ~

  image_server:
    id: ~
    name: { type: varchar, size: 30 }
    host: { type: varchar,size: 30 }

  room:
    id: ~
    name:       { type: varchar, size: 30 }
    comment:    { type: longvarchar }

  host:
    id: ~
    profile_id: ~
    room_id: ~
    number:         { type: varchar, size: 10 }
    ip_address:     { type: char, size: 15, required: true }
    mac_address:    { type: char, size: 17, required: true }
    comment:        { type: longvarchar }
    custom_conf:    { type: longvarchar }
    subnet_id:  ~
    pxe_file_id: ~
    created_at: ~
    updated_at: ~

  profile:
    id: ~
    name:    { type: varchar, size: 20 }
    comment: { type: longvarchar }

  pxe_file:
    id: ~
    name:     { type: varchar, size: 50 }
    filename: { type: varchar, size: 50 }

  image:
    id: ~
    name:     { type: varchar, size: 30, required: true }
    filename: { type: varchar,size: 50, required: true }
    restart:  { type: boolean, default: true }
    host_id:  ~

  command:
    id: ~
    started_at:   { type: timestamp }
    finished_at:  { type: timestamp }
    command:      { type: varchar, size: 200 }
    std_out_file: { type: varchar,size: 50 }
    std_err_file: { type: varchar,size: 50 }
    std_out:      { type: longvarchar }
    std_err:      { type: longvarchar }
    return_code:  { type: smallint, default: null }
    user_id:      { type: varchar,size: 50 } # user login
