propel:

  subnet:
    id: ~
    name: { type: varchar, size: 30 }
    ip_address: { type: char, size: 15, required: true }
    netmask:    { type: char, size: 15, required: true }

  drbl_server:
    id: ~
    name: { type: varchar, size: 30 }
    host: { type: varchar,size: 30 }

  room:
    id: ~
    name: { type: varchar, size: 30 }
    drbl_server_id: ~

  host:
    id: ~
    profile_id: ~
    room_id: ~
    number:         { type: varchar, size: 10 }
    ip_address:     { type: char, size: 15, required: true }
    mac_address:    { type: char, size: 17, required: true }
    comment:        { type: longvarchar }
    custom_conf:    { type: longvarchar }
    subnet_id: ~
    pxe_file_id: ~
    created_at: ~
    updated_at: ~

  profile:
    id: ~
    name: { type: varchar, size: 20 }

  pxe_file:
    id: ~
    filename: { type: varchar, size: 50 }

  image:
    id: ~
    name:     { type: varchar, size: 30 }
    filename: { type: varchar,size: 50 }
    restart:  { type: boolean, default: true }
