all:
  manitou:

    # NB ! Le chemin des scripts doivent être absolu ! 
    # Pour cela utiliser la variable %SF_ROOT_DIR% qui sera remplacée par la racine de Manitou

    # Création d'une image :
    #
    # params :
    #   - %image_filename%  Nom du fichier image à restaurer
    #   - %restart%         État des machine post-installation
    #   - %hosts_ip%        Adresses IP séparés par des espaces
    #   - %hosts_mac%       Adresses MAC séparés par des espaces (pour le wakeonlan)
    #   - %interface%       Interface du serveur DRBL pour le wakeonlan
    #   - %image_server%    Serveur DRBL à utiliser
    #   - %state%           État des machine post-installation (wait, reboot, poweroff)
    create_image_command: %SF_ROOT_DIR%/scripts/examples/create-image.sh %host_ip% %host_mac% %interface% %image_server% %state% %image_filename%

    # Restauration d'une image :s
    #
    # params :
    #   - %hosts_ip%        Adresses IP séparés par des espaces
    #   - %hosts_mac%       Adresses MAC séparés par des espaces (pour le wakeonlan)
    #   - %interface%       Interface du serveur DRBL pour le wakeonlan
    #   - %image_server%    Serveur DRBL à utiliser
    #   - %resize%          Redimentionner les partitions
    #   - %partition%       Partition à re
    #   - %image_filename%  Nom du fichier image à restaurer
    #   - %pre_run%         Exécuter le script PRE_RUN (0,1)
    #   - %post_run%        Exécuter le script POST_RUN (0,1)
    #   - %state%           État des machine post-installation (wait, reboot, poweroff)
    restore_image_command: %SF_ROOT_DIR%/scripts/examples/restore-image.sh %hosts_ip% %hosts_mac% %interface% %image_server% %resize% %partition% %state% %image_filename% %pre_run% %post_run%

    # Mise à jour du DNS après une modification liée à un host.
    # (Appelé à l'ajout/mdification/suppression d'une machine
    #
    # params :
    #   - %domain%          Zone forward
    #   - %reverse_domain%  Zone reverse
    #   - %hostname%        Hostname de la machine ajoutée/modifiée/supprimée
    #   - %host_ip%         Adresse IP
    ns_add_command: %SF_ROOT_DIR%/scripts/examples/ns-update.sh add %domain% %reverse_domain% %hostname% %host_ip%

    # Mise à jour du DNS après une modification liée à un host.
    # (Appelé à l'ajout/mdification/suppression d'une machine
    #
    # params :
    #   - %domain%          Zone forward
    #   - %reverse_domain%  Zone reverse
    #   - %host_ip%         Adresse IP
    ns_delete_command: %SF_ROOT_DIR%/scripts/examples/ns-update.sh delete %domain% %reverse_domain% %host_ip%

    # Mise à jour du DNS après une modification liée à un host.
    # (Appelé à l'ajout/mdification/suppression d'une machine
    #
    # params :
    #   - %conf_path%       Chemin où se situent les fichiers de conf du DHCP
    dhcp_update_command: %SF_ROOT_DIR%/scripts/examples/dhcp-update.sh %conf_path%

    # Création d'une image :
    #
    # Chemin absolu vers le répertoire où seront générés les fichiers de conf.
    # Ce repertoire doit exister et doit être versionné sous svn.
    dhcpd_conf_path: %SF_DATA_DIR%/rezodhcp/subnets

    # Utilisateur svn pour la mise à jour du dépôt contenant la conf dhcp
    svn_username: manitou
    svn_password: m4n1t00
